### ISSUE TITLE
Review Red Hat branding guidelines

### ISSUE THREAD

**Issue by seocam** [open-organization/open-decision-framework#41]
We have a new logo and new branding guidelines. What about releasing a new version with the updated branding?

**Comment by ruhbehka** [comment]
Hi there - We are actually working on an entirely new release of the Open Decision Framework, as our methodology has evolved considerably since this one was created. The scope of our internal decisions has increased from 5,000 participants (when this was created) to 15,000+ now, so we needed to do a fairly big overhaul. Hoping to have a first draft out for reactions and feedback in early 2021, and this will be a web-based interface (HTML etc.) with the new branding. I'm inclined to keep the old branding on the old version, rather than refresh it now.

**Comment by seocam** [comment]
Thanks for letting me know @ruhbehka! Where can I see this version? Are you following the "release early, release often"? :P

**Comment by ruhbehka** [comment]
Oh gosh, right now it's a giant mess spread across a messy document (which grew to an unweildy 108 pages), some sketches from a designer on suggested format, and a couple different presentation decks to try and simplify/organize. Honestly our biggest challenge has been that each person who joins the first attempt to simplify / streamline the content... ends up making it more complicated and bigger, plus stops reading 25% of the way through, so we have to keep scaling back and start over. We are finally at a place where I _almost_ have it in a format that can be easily reviewed by others, so I'm trying to hold people off on trying to poke around and give me feedback until then.

That being said, if you're curious and just want to look over everything, I'm more than happy to share it, as long as you don't judge the future by the present state. ;) 

If you're internal to Red Hat, ping me on Hangouts Chat and I'll add you to the docs to look around, if you promise not to give me any feedback yet. Haha. 

If you're external to Red Hat, I could probably give you access under the same conditions, I'd just need an email address that can access Google docs.

**Comment by seocam** [comment]
Thanks for the sincerity @ruhbehka!

When I first open this issue I was internal to Red Hat but I'm no longer with you as an employee. Currently I'm leading a tech team in a fintech and I really want to apply open management practices in my new job role and at some point contribute to the framework as well.

I'd be happy with read-only access just as sneak-peak to the new document. My email is my github user at gmail.

Thanks!!

**Comment by ruhbehka** [comment]
Access granted @seocam . :)

**Comment by jimmysjolund** [comment]
As ownership has now been transferred to The Open Organization, we will start the rebranding to the Open Org brand.

If someone still have access to the discussed updates of content above, I'm very curious to read those as I have not found any working links anymore?
