### ISSUE TITLE
Clarify what this is, why people might be interested

### ISSUE THREAD

**Issue by nealmcb** [open-organization/open-decision-framework#44]
Intriguing, but confusing....

Especially given that this is an unusual sort of repo, I suggest you avoid recursive descriptions. From the top of the README:

> Open Decision Framework: A community version of the Open Decision Framework

* What is it, actually?
  * A piece of software? That's what people expect to see on GitHub.
  * A body of knowledge? Seems like the case here at least in part.
  * A decision-making methodology? Also seems likely in part.
* To be used how?
  * You might want to move the Real-world examples section higher.

Based on the answers, also update the "About" bylines in GitHub

**Comment by jimmysjolund** [comment]
Updated About with "A community version of the Open Decision Framework - A flexible, open approach to making decisions and leading projects"
