### ISSUE TITLE
Rebrand the ODF with The Open Organization

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/open-decision-framework#55]
As all material is still an old brand of Red Hat we will start updating all material with the brand of The Open Organization.

**Comment by semioticrobotic** [comment]
Thanks for getting this started, @jimmysjolund. I'm sure you have it covered, but if I can be of any assistance, just tag me in an issue or pull request.

**Comment by semioticrobotic** [comment]
Nice work with this so far, @jimmysjolund! We've rebranded the informational presentation about the framework with https://github.com/open-organization/open-decision-framework/commit/5bc1a0f0d6ab1f1e1cfa0792f4b4ab8c5961d019. Have you identified additional areas of work here, or would you like to close?

**Comment by semioticrobotic** [comment]
Ah. It looks like we may also wish to rebrand [the maturity model](https://github.com/open-organization/open-decision-framework/tree/master/maturity-model), too. So maybe we keep this open until that work is complete.

**Comment by jimmysjolund** [comment]
We could probably close it and do new issues for any other updates.
