### ISSUE TITLE
Rebranding missed one mention of Red Hat

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/open-decision-framework#62]
On slide 10: Phase or activity: Launch, Deploy, Close
in the bullet list it says:

> Demonstrate alignment with Red Hat's strategy, mission, culture, and values

Should be updated with "your" or "the community strategy ..."

**Comment by jimmysjolund** [comment]
As I have the original Google slide deck on a non-public account I will need to do the update.

**Comment by jimmysjolund** [comment]
PR #67

**Comment by semioticrobotic** [comment]
Merged and closing!
