### ISSUE TITLE
Update Planet4 Example with link to deck

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/open-decision-framework#64]
In the README there is a deadlink on the Planet 4 example. I happen to own the original deck so we can either link to it or I can export a PDF or something and stick it directly in this repo:

https://docs.google.com/presentation/d/1ldc9dmV1dcm7o1Sjw4RLV6fEAV7ui6nvblhxduZSR0o/edit#slide=id.p4

**Comment by semioticrobotic** [comment]
There's always the [series landing page](https://opensource.com/tags/open-organization-greenpeace), too!

**Comment by LauraHilliger** [comment]
good call, fixed: https://github.com/open-organization/open-decision-framework/pull/66
